spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usermanagementdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: UserManagementAPI

server:
  port: 8080
